/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package org.kurokami.proyectovirtualizacion;

import org.kurokami.proyectovirtualizacion.conexion.OperacionesSql;

/**
 *
 * @author marcos
 */
public class Ventana extends javax.swing.JFrame {
    
    private OperacionesSql operaciones;
    /**
     * Creates new form Ventana
     */
    public Ventana() {
        initComponents();
        operaciones = new OperacionesSql();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        seleccion_pc = new javax.swing.JComboBox<>();
        boton_insertar = new javax.swing.JButton();
        dato_insertar = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jToggleButton1 = new javax.swing.JToggleButton();
        dato_mostrado = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        seleccion_pc.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "PC 1", "PC 2", "PC 3", "PC 4"}));
        getContentPane().add(seleccion_pc, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 30, 320, -1));

        boton_insertar.setText("Insertar");
        boton_insertar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_insertarActionPerformed(evt);
            }
        });
        getContentPane().add(boton_insertar, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 70, 110, -1));
        getContentPane().add(dato_insertar, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 70, 210, -1));

        jLabel1.setText("PC");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 50, 20));

        jLabel2.setText("Dato");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 50, 20));

        jToggleButton1.setText("Actualizar Dato");
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jToggleButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, -1, -1));

        dato_mostrado.setFont(new java.awt.Font("sansserif", 0, 24)); // NOI18N
        dato_mostrado.setText("0");
        getContentPane().add(dato_mostrado, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 170, 260, 30));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void boton_insertarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_insertarActionPerformed
        // TODO add your handling code here:
        String texto = this.dato_insertar.getText();
        org.kurokami.proyectovirtualizacion.conexion.OperacionesSql.pcSeleccionada = Integer.valueOf(this.seleccion_pc.getSelectedIndex());
        if (!(texto.equals(""))){
            operaciones.insertarDato(Integer.valueOf(texto));
        }
    }//GEN-LAST:event_boton_insertarActionPerformed

    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed
        // TODO add your handling code here:
        int cambiar = operaciones.getTotal();
        this.dato_mostrado.setText(Integer.toString(cambiar));
    }//GEN-LAST:event_jToggleButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ventana().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton boton_insertar;
    private javax.swing.JTextField dato_insertar;
    private javax.swing.JLabel dato_mostrado;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JComboBox<String> seleccion_pc;
    // End of variables declaration//GEN-END:variables
}
